### ISSUE TITLE
Vite -ssg - missing exports

### ISSUE THREAD

**Issue by whatisaghostwriter** [wobsoriano/vagmi#1]
Hey I appreciate the work you've done on this library. As for continuing my implementation I've run into something I think could be fixed easily but I don't know what's causing me trouble here
![Capture](https://user-images.githubusercontent.com/34256092/172043153-67a89d23-d8e1-4219-b112-09912a8debb0.PNG)
I followed the example but it doesn't use vite-ssg. 
On this repo https://github.com/rainfinity/ninjas.git  in matterjs branch

**Comment by wobsoriano** [comment]
Oh, thanks for this. It confirmed one of my issues

**Comment by wobsoriano** [comment]
Can you try with v0.1.7?

**Comment by whatisaghostwriter** [comment]
It works, thanks now I'm dealing with some other problem concerning unenv polyfills / vue-i18n.

**Comment by wobsoriano** [comment]
Check if this will help with your polyfills

https://github.com/wobsoriano/vagmi/blob/master/examples/dev/vite.config.ts

**Comment by whatisaghostwriter** [comment]
thanks brother that solution works better than the unenv way to do it with my setup. My site is able to be deployed now
