### ISSUE TITLE
Nuxt 3 silent fail when using WalletConnect in SSG

### ISSUE THREAD

**Issue by ennioVisco** [wobsoriano/vagmi#2]
Hello,

You can find a minimal reproduction here: https://codesandbox.io/s/cranky-dijkstra-vrlg3i?file=/nuxt.config.ts

Essentially, when running in dev environment (`yarn dev`), the WalletConnect popup works correctly, while when running in client side mode (i.e. by hosting `.output/public` from `npx nuxi generate` in a web hosting of any kind), the popup doesn't work but it doesn't throw any errors.

I'm using polyfills as from https://github.com/nuxt/framework/discussions/4393.

**Comment by wobsoriano** [comment]
I'm going to check this later. Thank you!

**Comment by ennioVisco** [comment]
@wobsoriano any update on this? 
I really need it. Let me know if I can help in some way :)

**Comment by wobsoriano** [comment]
Just checked now, you can use `onError` when connecting to see a possible error

```ts
const { connect } = useConnect({
  onError(err) {
    console.log(err)
  }
});
```

I tried your code with an `onError` and I got 

```bash
ReferenceError: global is not defined
```

**Comment by wobsoriano** [comment]
Since you're using it only in client, you can uninstall `@esbuild-plugins/node-globals-polyfill` and `@esbuild-plugins/node-modules-polyfill` and do this instead:

```bash
yarn add buffer events process util
``` 

```ts
import { defineNuxtConfig } from "nuxt";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  ssr: false,

  vite: {
    define: {
      global: 'globalThis',
    },
    resolve: {
      alias: {
        process: 'process/browser',
        util: 'util',
      },
    },
  }
});
```

And in your `app.vue`

```html
<script setup>
import process from "process";
import { Buffer } from "buffer";
import EventEmitter from "events";

window.global = window
window.process = process;
window.Buffer = Buffer;
window.EventEmitter = EventEmitter;
</script>

<template>
  <div>
    <NuxtPage />
  </div>
</template>
```

**Comment by ennioVisco** [comment]
@wobsoriano I didn't know about the onError callback, thanks a lot! 
Your suggestion makes sense, but there should be some polyfills that can be loaded in the vite config... I'll check the tons of issues in the nuxt 3 repo and come back asap when I find a better solution :)

**Comment by wobsoriano** [comment]
the polyfill above is based on the example here

https://github.com/tmm/wagmi/tree/main/examples/vite-react

**Comment by ennioVisco** [comment]
@wobsoriano yes, but for example the `global : globalThis` should not be needed starting from next 3 RC.4, according to: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.4
While for the rest, maybe it works in production, but it doesn't in dev environment where nuxt is running through node. Ideally we should find a solution that works in both the environments.

**Comment by ennioVisco** [comment]
Actually, your solution seem to work just fine in both server-side and client-side. So, I'll close the issue :)
