### ISSUE TITLE
configureChains | TS2305: Module '"vagmi"' has no exported member 'configureChains'.

### ISSUE THREAD

**Issue by re2005** [wobsoriano/vagmi#23]
Hi, Thanks for this repo.

I'm trying to use but it's not working: `configureChains` seems to not be exported.

![Screenshot 2022-07-03 at 08 45 27](https://user-images.githubusercontent.com/2920357/177028394-8fecdef6-3e3c-4647-b384-abf40da937ac.png)

**Comment by wobsoriano** [comment]
Fixed in v0.1.16. Just update to the latest version. Thank you!
