### ISSUE TITLE
Should the balance update when switching accounts on metamask?

### ISSUE THREAD

**Issue by re2005** [wobsoriano/vagmi#24]
I'm new to the `vagami` also the react version `wagmi.sh` so I'm don't know if this is just not a feature or if it should work as I'm thinking.

Connect Metamask allow two accounts.

1- When switching the accounts you see the address changing. So I would expect that if you using the balance hook, it would also be updated.

```
const { data, isError, isLoading } = useBalance({
    addressOrName: address.value,
});
```

But doesn't change.

I can watch for changes and fetch myself the balance, but how to setup it back inside of the `useBalance` hook?

```
watch(activeConnector, (val) => {
  console.log('Active connector', val);
});
```

Thanks for any direction given!

**Comment by wobsoriano** [comment]
I'm working on updates. Looks like a ton of changes in wagmi

**Comment by re2005** [comment]
Balance is now being updated (v0.1.18) when switching accounts. 

Next here would be also update the balance when Metamask updated it. 

Lets say I've done a transfer so my balance went lower or higher, would be great it the balance gets updated, OR any method for me to call to request updateBalance.

Cheers!

**Comment by wobsoriano** [comment]
Try with the `refetch` method:

```ts
const { address } = useAccount()
const { data, refetch } = useBalance({
    addressOrName: address,
})

refetch()
```
