### ISSUE TITLE
typo getVagmiFuntionsWithPath

### ISSUE THREAD

**Issue by re2005** [wobsoriano/vagmi#25]
getVagmiFuntionsWithPath

should be

getVagmiFunctionsWithPath

![Screenshot 2022-07-03 at 19 29 49](https://user-images.githubusercontent.com/2920357/177050847-75ea2a59-894e-4d94-9f8d-a23b8d0d9845.png)

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vagmi/commit/4742b29afcc20f2f3be16340ddf5cec4e370014f
