### ISSUE TITLE
Please update the readme on how to run it locally

### ISSUE THREAD

**Issue by re2005** [wobsoriano/vagmi#26]
I've installed and it seems that a few bits are missing to properly configure and run it locally.

Dependencies missing
`"@rollup/plugin-inject": "^4.0.4",`

maybe `@vueuse/metadata`

Thanks

**Comment by wobsoriano** [comment]
Basic example here

https://github.com/wobsoriano/vagmi/tree/master/examples/dev

**Comment by re2005** [comment]
Thanks Robert, I see the example.

For me it doesn't work immediately.

![vagami-example](https://user-images.githubusercontent.com/2920357/177099971-f546aba0-f651-418f-8c00-1362573396ac.png)

I need to do something else in order to run the example and also be able to contribute to this repo.
Maybe if you describe a little bit how to run both the example and the plugin itself would be nice.

Cheers.

**Comment by wobsoriano** [comment]
Start a fresh project with vite and copy paste the example
