### ISSUE TITLE
Add Gnosis Safe ?

### ISSUE THREAD

**Issue by re2005** [wobsoriano/vagmi#27]
Does it support `Gnosis Safe` as a option for the connectors, once running inside the Gnosis Safe <iframe> ?

Thanks

**Comment by re2005** [comment]
A similar connector would be great.

Something like:
https://github.com/safe-global/safe-apps-sdk/tree/master/packages/safe-apps-wagmi

**Comment by wobsoriano** [comment]
> A similar connector would be great.
> 
> Something like: https://github.com/safe-global/safe-apps-sdk/tree/master/packages/safe-apps-wagmi

Just do the instructions but for Vue 3.

**Comment by wobsoriano** [comment]
We have a discussions tab for suggestions and stuff

https://github.com/wobsoriano/vagmi/discussions

**Comment by re2005** [comment]
Thanks @wobsoriano could you please point to the where are the Vue3 instructions ?

`@gnosis.pm/safe-apps-wagmi` but getting lots of errors.

Thanks
