### ISSUE TITLE
wagmi integration

### ISSUE THREAD

**Issue by ennioVisco** [wobsoriano/vagmi#29]
I just noticed that the core of wagmi (https://wagmi.sh/docs/client) is framework-agnostic, why not reuse it and re-implement only the composables?

**Comment by wobsoriano** [comment]
@ennioVisco If you check the composables, it's using `@wagmi/core`:

https://github.com/wobsoriano/vagmi/blob/master/packages/vagmi/src/composables/accounts/useAccount.ts

**Comment by ennioVisco** [comment]
> @ennioVisco If you check the composables, it's using `@wagmi/core`:
> 
> https://github.com/wobsoriano/vagmi/blob/master/packages/vagmi/src/composables/accounts/useAccount.ts

I apologize, I didn't see it in the package.json and I thought it wasn't relying on it

**Comment by wobsoriano** [comment]
No worries @ennioVisco ! 😄
