### ISSUE TITLE
WalletConnect

### ISSUE THREAD

**Issue by callmejm** [wobsoriano/vagmi#34]
Hi, I able to connect to WalletConnect, but how can I sendTransaction ?

**Comment by maxschnaider** [comment]
but I prefer to go with typechain https://www.npmjs.com/package/typechain

**Comment by youthinn** [comment]
> 

Is there a complete method of using trading? I built it with vue3 but couldn't find a way to send transactions

**Comment by callmejm** [comment]
sorry to tell that I have give up on this repo, use react + wagmi instead
