### ISSUE TITLE
Contract Interaction

### ISSUE THREAD

**Issue by jewelsonn** [wobsoriano/vagmi#35]
Why are the main features like contract Interaction left out? I am unable to communicate with my contacts yet. I hope someone is working on implementing this ☺️ because right now I have to go round about ways to do that using ethers.js and it's troublesome during builds.

I am currently using quasar, And Vagmi to create a dapp and the process is so simple.

Currently I am calling useSigner to passon the provider to the contract but I am getting the error:  
` TypeError: 'get' on proxy: property 'provider' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Web3Provider>' but got '#<Web3Provider>')` 

even if I use markRaw I end up getting same error. 

But it's causing some issues. Is there a proper way to interact with Contract  functions using Vagmi?

**Comment by maxschnaider** [comment]
same for me

**Comment by maxschnaider** [comment]
I'm currently using raw func from core to get signer:

```
import { fetchSigner } from '@wagmi/core'

const signer = await fetchSigner()
```

You can wrap it up in your custom composable
